# Quick Intro

## Python 数据类型 - List

In [3]:
a = [1, 2, 3] 
print(type(a))            # Prints "<class 'list'>"
print(len(a))            # Prints "3"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'list'>
3
1 2 3
[5, 2, 3]


## Python 数据类型 - List vs Tuple

In [22]:
#tuple 
tp = (1,2,3)
tp, type(tp)

((1, 2, 3), tuple)

In [28]:
li = [1,2,3]
print(li, type(li))
li.append(5)
del li[0]
li

[1, 2, 3] <class 'list'>


[2, 3, 5]

(1,2,3).append(5)

AttributeError: 'tuple' object has no attribute 'append'


tuple/元组 不可更改 immutable

In [21]:
np.array?

## Numpy 数据类型 - ndarray

In [7]:
import numpy as np

(numpy.ndarray, 3)

所有ndarray 都有一个属性, shape

In [9]:
a = np.array([1, 2, 3])
type(a), len(a), a.shape

(numpy.ndarray, 3, (3,))

In [11]:
amrow = np.array([[1, 2, 3]])
amrow.shape # 一行三列

(1, 3)

Transpose 转置

In [13]:
amcol = amrow.T
amcol.shape

(3, 1)

In [14]:
amcol

array([[1],
       [2],
       [3]])

多维数据结构, 如矩阵, 都是以list of lists的形式存储

In [19]:
a = [[1,2], [4,5], [7,8]]

len(a)


3

In [17]:
anp = np.array(a)
type(anp), len(anp), anp.shape 

(numpy.ndarray, 3, (3, 2))

anp是一个三行两列的二维数组, 也是一个矩阵

In [21]:
anp

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
anp[0], anp[1], anp[2]

(array([1, 2]), array([4, 5]), array([7, 8]))

### numpy的访问方式: 访问 第2行, 第2列

In [24]:
anp[1 ,1]

5

python的访问方式: 访问 第1个列表的第1个元素 (从0开始)

In [25]:
anp[1][1]

5

### 访问ndarray

In [3]:
import numpy as np

a = np.array([1, 2, 3])   # Create a 1d array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a 2d array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


# 创建数组

## 手动创建数组

### 1D  1维数组

In [26]:
a = np.array([0, 1, 2, 3])
print(a)
print(type(a))
print(len(a))
print(a.ndim)
print(a.shape)

[0 1 2 3]
<class 'numpy.ndarray'>
4
1
(4,)


### nD, n>1 多维数组

In [4]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

print(b)
print(type(b))
print(len(b)) # returns the size of the first dimension
print(b.ndim) 
print(b.shape)

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>
2
2
(2, 3)


In [28]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


array([[[1],
        [2]],

       [[3],
        [4]]])

In [32]:
b

array([[0, 1, 2],
       [3, 4, 5]])

### 访问第1行 (从0开始)

In [5]:
b[1, :]

array([3, 4, 5])

### 访问第1列 (从0开始)

In [31]:
b[:, 1]

array([1, 4])

In [6]:
np.array?

## 使用函数创建数组

### 等间距的数组

In [6]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange?

In [7]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

In [8]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

### 指定元素个数的数组

In [8]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [9]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

从1到10, 包含10, 生成15个浮点数

In [13]:
np.linspace(1, 10, 15)

array([  1.        ,   1.64285714,   2.28571429,   2.92857143,
         3.57142857,   4.21428571,   4.85714286,   5.5       ,
         6.14285714,   6.78571429,   7.42857143,   8.07142857,
         8.71428571,   9.35714286,  10.        ])

### 获得帮助

In [10]:
np.linspace?

In [15]:
np.ones?

In [11]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
b = np.zeros((2, 2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [38]:
six = np.full([6,6], 666)
six

array([[666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666, 666]])

In [35]:
np.full?

In [13]:
c = np.eye(3)
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## ndarray操作

### reshape

In [36]:
np.eye?

In [14]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.arange(12), np.arange(12).shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [39]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Transpose 转置

In [65]:
np.arange(12).reshape(3,4).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
np.transpose(np.arange(12).reshape(3,4))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# 常见数据类型

In [15]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [16]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

## 指定使用某种数据类型

In [67]:
c = np.array([1, 2, 3], dtype=float)
c.dtype, c

(dtype('float64'), array([ 1.,  2.,  3.]))

## 默认数据类型为float

In [18]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

In [80]:
a = np.full(5, 256).astype(np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [81]:
a = np.full(5, 256).astype(np.int32)
a

array([256, 256, 256, 256, 256])

In [83]:
1.2345465657e9

1234546565.7

## 复数, j而不是i是工程上的惯例

In [19]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

## 布尔

In [20]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

## 字符串

In [21]:
f = np.array(['Bonjour', 'Hello', 'Hallo',])
f.dtype     # <--- strings containing max. 7 letters  

dtype('<U7')

# 数组的索引与切割

## 索引

In [22]:
a = np.arange(10)
a, a[0], a[2], a[-1]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 0, 2, 9)

In [23]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [25]:
a[1, 1]

1

In [26]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [27]:
a[1]

array([0, 1, 0])

## 切割

In [84]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

### 和python一样, 最后的索引是不包含在切割出的数组中的

In [86]:
a[:4]

array([0, 1, 2, 3])

### by default, start is 0, end is the last and step is 1

In [30]:
a[1:3], a[::2], a[3:]

(array([1, 2]), array([0, 2, 4, 6, 8]), array([3, 4, 5, 6, 7, 8, 9]))

## 复杂操作

In [31]:
a = np.arange(10)
a[5:] = 10
a

b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## 图示

In [87]:
m = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
m

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [91]:
m[4:,4:]

array([[44, 45],
       [54, 55]])

![A small illustrated summary of NumPy indexing and slicing…](numpy_indexing.png "A small illustrated summary of NumPy indexing and slicing…")

## Fancy Indexing

### Boolean Masking

In [100]:
9 % 3 == 0

True

In [102]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

逐位操作 element-wise operations

In [103]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a * 5 / 10

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [106]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
b ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [113]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [114]:
a % 3 == 0

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False], dtype=bool)

将a中所有能被3整除的元素组成一个新的ndarray

In [116]:
a[a % 3 == 0]

array([ 3,  0,  9,  6,  0, 12])

In [136]:
b = np.arange(1, 13).reshape(3,4) ** 2
b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [137]:
b % 5 == 0

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False]], dtype=bool)

In [138]:
(b % 5).shape == b.shape

True

In [140]:
b[b % 5 == 0 ]

array([ 25, 100])

In [35]:
mask = (a % 3 == 0)
a[mask] # or,  a[a%3==0], extract a sub-array with the mask

array([ 3,  0,  9,  6,  0, 12])

### 使用数组索引数组

In [36]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [38]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [92]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [99]:
m[[0,-1], :] = 0

In [98]:
m

array([[ 0,  0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [ 0,  0,  0,  0,  0,  0]])

![Fancy Indexing](numpy_fancy_indexing.png "Fancy Indexing")