In [3]:
import numpy as np
threed = np.linspace(0, 10, 90)
threed.reshape(3, 5, 6).shape

(3, 5, 6)

In [4]:
threed.reshape(3, 5, 6).transpose(1,0,2).shape

(5, 3, 6)

In [8]:
np.reshape([0,1], (1,2,1)).shape

(1, 2, 1)

In [9]:
np.asarray([0,1]).reshape((1,2,1))

array([[[0],
        [1]]])

In [10]:
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [17]:
a = np.arange(0,51,10)[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [18]:
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [21]:
np.arange(0,51,10).shape

(6,)

In [24]:
np.arange(0,51,10)[:, np.newaxis].shape

(6, 1)

In [25]:
c = a + b

In [26]:
c.shape

(6, 6)

In [33]:
c[:, np.newaxis, :].shape

(6, 1, 6)

In [35]:
c[np.newaxis, :, :].shape

(1, 6, 6)

In [32]:
c[:, :,np.newaxis].shape

(6, 6, 1)

In [36]:
c[np.newaxis, :, :].shape

(1, 6, 6)

In [37]:
a=np.arange(10)
a[:,np.newaxis].shape

(10, 1)

In [38]:
a.shape

(10,)